# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('gender', models.CharField(max_length=264)),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(null=True)),
                ('position', models.CharField(max_length=264)),
                ('department', models.CharField(max_length=264)),
                ('operational_unit_id', models.IntegerField()),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('extension', models.IntegerField()),
                ('manager_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee.mployee_id+', to='demo.Employee')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee.manager_id+', to='demo.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential', models.IntegerField()),
                ('performance', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('notes', models.TextField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Management.employee_id+', to='demo.Management')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Management.manager_id+', to='demo.Management')),
            ],
        ),
    ]
