# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='permissions_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='performance',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='potential',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
