# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='management',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee.employee_id+', to='demo.Employee'),
        ),
        migrations.AlterField(
            model_name='management',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='management',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee.employee_id+', to='demo.Employee'),
        ),
    ]
