# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='location',
            name='assigned_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_location', to='demo.Employee'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='managment_relationship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='demo.Supervision'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='subordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='demo.Employee'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='demo.Manager'),
        ),
    ]
