# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20170606_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='subordiante',
            new_name='managment_relationship',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='supervisor',
        ),
        migrations.AlterField(
            model_name='supervision',
            name='subordinate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees+', to='demo.Employee'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors+', to='demo.Manager'),
        ),
    ]
