# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20170604_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(null=True),
        ),
    ]
