# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20170604_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='operational_unit_id',
            field=models.IntegerField(null=True),
        ),
    ]
