# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20170604_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=264),
        ),
    ]
