# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20170604_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demo.Employee')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('permissions_level', models.IntegerField()),
            ],
            bases=('demo.employee',),
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='management',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='management',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='management',
            name='manager_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='notes',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='Management',
        ),
        migrations.AddField(
            model_name='supervision',
            name='subordiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='demo.Employee'),
        ),
        migrations.AddField(
            model_name='supervision',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='demo.Manager'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='manager_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='managment_relationships',
            field=models.ManyToManyField(related_name='refers_to', through='demo.Supervision', to='demo.Employee'),
        ),
        migrations.AddField(
            model_name='rating',
            name='subordiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='demo.Supervision'),
        ),
        migrations.AddField(
            model_name='rating',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='demo.Supervision'),
        ),
    ]
